version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - frontend/.env.local

  backend:
    ports:
      - 4061:4061
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src

